# Generated by Django 4.0.5 on 2022-06-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('boby', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
