# Generated by Django 4.0.5 on 2022-06-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='boby',
            new_name='body',
        ),
    ]
